//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvvm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mvvm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///{ &apos;name&apos;: &apos;Andi Theke&apos;, &apos;birthday&apos;: &apos;15.08.1999&apos;, &apos;gender&apos;: 0 },
        ///{ &apos;name&apos;: &apos;Sören Hagen&apos;, &apos;birthday&apos;: &apos;15.08.1999&apos;, &apos;gender&apos;: 0 },
        ///{ &apos;name&apos;: &apos;Hildegardt Schröder&apos;, &apos;birthday&apos;: &apos;15.08.1999&apos;, &apos;gender&apos;: 1 },
        ///{ &apos;name&apos;: &apos;Gertrude Müller&apos;, &apos;birthday&apos;: &apos;15.08.1999&apos;, &apos;gender&apos;: 1 },
        ///{ &apos;name&apos;: &apos;Apache Helicopter&apos;, &apos;birthday&apos;: &apos;15.08.1999&apos;, &apos;gender&apos;: 2 }
        ///].
        /// </summary>
        internal static string JsonData {
            get {
                return ResourceManager.GetString("JsonData", resourceCulture);
            }
        }
    }
}
