//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvvm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mvvm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;name&quot;: &quot;12A&quot;
        ///}.
        /// </summary>
        internal static string Class_1 {
            get {
                return ResourceManager.GetString("Class_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;name&quot;: &quot;12B&quot;
        ///}.
        /// </summary>
        internal static string Class_2 {
            get {
                return ResourceManager.GetString("Class_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;name&quot;: &quot;11A&quot;
        ///}.
        /// </summary>
        internal static string Class_3 {
            get {
                return ResourceManager.GetString("Class_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;name&quot;: &quot;Rene Kuester&quot;,
        ///        &quot;birthday&quot;: &quot;17.07.1998&quot;,
        ///        &quot;gender&quot;: 0,
        ///        &quot;grades&quot; : [1., 2., 3.]
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;Peter Gottschalk&quot;,
        ///        &quot;birthday&quot;: &quot;23.08.2001&quot;,
        ///        &quot;gender&quot;: 0,
        ///        &quot;grades&quot; : [3., 2., 3.]
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;Mike Lang&quot;,
        ///        &quot;birthday&quot;: &quot;01.03.1998&quot;,
        ///        &quot;gender&quot;: 1,
        ///        &quot;grades&quot; : [1., 2., 1.]
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;Janina Schwarz&quot;,
        ///        &quot;birthday&quot;: &quot;06.12.2002&quot;,
        ///        &quot;gender&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Students_1 {
            get {
                return ResourceManager.GetString("Students_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;name&quot;: &quot;Karin Klein&quot;,
        ///        &quot;birthday&quot;: &quot;17.07.1998&quot;,
        ///        &quot;gender&quot;: 1,
        ///        &quot;grades&quot;: [1., 2.]
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;Jessika Weisz&quot;,
        ///        &quot;birthday&quot;: &quot;13.09.2001&quot;,
        ///        &quot;gender&quot;: 1,
        ///        &quot;grades&quot;: [2., 2.]
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;Ralph Kaufmann&quot;,
        ///        &quot;birthday&quot;: &quot;24.12.1998&quot;,
        ///        &quot;gender&quot;: 0,
        ///        &quot;grades&quot;: [3., 1.]
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;Michelle Fassbinder&quot;,
        ///        &quot;birthday&quot;: &quot;01.03.2002&quot;,
        ///        &quot;gender&quot;: 1,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Students_2 {
            get {
                return ResourceManager.GetString("Students_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;name&quot;: &quot;Erik Durr&quot;,
        ///        &quot;birthday&quot;: &quot;24.03.1998&quot;,
        ///        &quot;gender&quot;: 0,
        ///        &quot;grades&quot;: [1.]
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;Mathias Burger&quot;,
        ///        &quot;birthday&quot;: &quot;29.01.2001&quot;,
        ///        &quot;gender&quot;: 0,
        ///        &quot;grades&quot;: [4.]
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;Tobias Zweig&quot;,
        ///        &quot;birthday&quot;: &quot;05.04.1998&quot;,
        ///        &quot;gender&quot;: 0,
        ///        &quot;grades&quot;: [2.]
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;Sandra Cole&quot;,
        ///        &quot;birthday&quot;: &quot;21.08.2002&quot;,
        ///        &quot;gender&quot;: 1,
        ///        &quot;grades&quot;: [1.]
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Students_3 {
            get {
                return ResourceManager.GetString("Students_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;name&quot;: &quot;Tobias Bosch&quot;,
        ///    &quot;birthday&quot;: &quot;29.04.1974&quot;,
        ///    &quot;gender&quot;: 0
        ///}.
        /// </summary>
        internal static string Teacher_1 {
            get {
                return ResourceManager.GetString("Teacher_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;name&quot;: &quot;Torsten Gersten&quot;,
        ///    &quot;birthday&quot;: &quot;18.10.1967&quot;,
        ///    &quot;gender&quot;: 0
        ///}.
        /// </summary>
        internal static string Teacher_2 {
            get {
                return ResourceManager.GetString("Teacher_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;name&quot;: &quot;Martina Barth&quot;,
        ///    &quot;birthday&quot;: &quot;27.07.1981&quot;,
        ///    &quot;gender&quot;: 0
        ///}.
        /// </summary>
        internal static string Teacher_3 {
            get {
                return ResourceManager.GetString("Teacher_3", resourceCulture);
            }
        }
    }
}
